server:
  port: 8084
dubbo:
  protocol:
    name: tri
    port: 28084
  application:
    name: user
    register-mode: instance
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: '031027'
spring:
  data:
    redis:
      port: 6379
      host: 101.201.47.132
      password: '031027'
  datasource:
    username: fadai
    password: '031027'
    url: jdbc:mysql://101.201.47.132:3306/train
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: user
jasypt:
  encryptor:
    # 加密的盐值，为了安全，该配置可以放在启动参数或者命令行参数中
    password: fa7bd4edd42448aea8c9484fbce6e8cd
    # 加密所采用的算法
    algorithm: PBEWITHHMACSHA512ANDAES_256
mybatis:
  configuration:
    map-underscore-to-camel-case: true