spring:
  data:
    redis:
      port: 6379
      host: 101.201.47.132
      password: '031027'
  rabbitmq:
    host: 101.201.47.132
    port: 5672
    username: fadai
    password: '031027'
    publisher-confirm-type: correlated
  application:
    name: buyTickets
dubbo:
  application:
    name: buyTickets
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: '031027'
server:
  port: 8080
